import { Role } from './types';

export default [
  {
    id: 'UBGP2J2PK',
    email: 'ld@localizedirect.com',
    names: ['Lynh'],
    role: Role.MEMBER,
  },
  {
    id: 'UK4KAN0QL',
    email: 'tn@localizedirect.com',
    names: ['Truong'],
    role: Role.MEMBER,
  },
  {
    id: 'UL85VPR89',
    email: 'gn@localizedirect.com',
    names: ['Giang'],
    role: Role.ADMIN,
  },
  {
    id: 'ULNN8L7LY',
    email: 'dng@localizedirect.com',
    names: ['Duong Nguyen'],
    role: Role.MEMBER,
  },
  {
    id: 'UNLSN00G4',
    email: 'vtl@localizedirect.com',
    names: ['Trong'],
    role: Role.MEMBER,
  },
  {
    id: 'UNPUPE7SQ',
    email: 'kp@localizedirect.com',
    names: ['Khanh Pham'],
    role: Role.MEMBER,
  },
  {
    id: 'U010UQL36JV',
    email: 'th@localizedirect.com',
    names: ['Tan'],
    role: Role.MEMBER,
  },
  {
    id: 'U011EL24BPS',
    email: 'tin@localizedirect.com',
    names: ['Tin'],
    role: Role.ADMIN,
  },
  {
    id: 'U012QKY7YJW',
    email: 'hh@localizedirect.com',
    names: ['Hieu Huynh'],
    role: Role.MEMBER,
  },
  {
    id: 'U0183USRRFF',
    email: 'sn@localizedirect.com',
    names: ['Sang'],
    role: Role.MEMBER,
  },
  {
    id: 'UUEGP229F',
    email: 'dp@localizedirect.com',
    names: ['Dung'],
    role: Role.MEMBER,
  },
  {
    id: 'U01QSGJTA07',
    email: 'qv@localizedirect.com',
    names: ['Quang Vo'],
    role: Role.MEMBER,
  },
  {
    id: 'U021JSYHUG5',
    email: 'pv@localizedirect.com',
    names: ['Phu'],
    role: Role.MEMBER,
  },
  {
    id: 'U026KACHTM4',
    email: 'pia@localizedirect.com',
    names: ['Pia'],
    role: Role.ADMIN,
  },
  {
    id: 'U02ARBPCHSQ',
    email: 'ldv@localizedirect.com',
    names: ['Long'],
    role: Role.MEMBER,
  },
  {
    id: 'U02E63EMS1Z',
    email: 'hm@localizedirect.com',
    names: ['Huong'],
    role: Role.MEMBER,
  },
  {
    id: 'U02ED23PKGD',
    email: 'tc@localizedirect.com',
    names: ['Steve'],
    role: Role.MEMBER,
  },
  {
    id: 'U02EM3B7ZH8',
    email: 'tnn@localizedirect.com',
    names: ['Thy'],
    role: Role.MEMBER,
  },
  {
    id: 'U02SFB71Y66',
    email: 'nn@localizedirect.com',
    names: ['Andy', 'Nha'],
    role: Role.MEMBER,
  },
  {
    id: 'U037K4B22U8',
    email: 'nnc@localizedirect.com',
    names: ['Jason', 'Cuong'],
    role: Role.MEMBER,
  },
  {
    id: 'UGMCN8NAV',
    email: 'cm@localizedirect.com',
    names: ['Chau Nguyen'],
    role: Role.MEMBER,
  },
  {
    id: 'U03HSG0S599',
    email: 'sla@localizedirect.com',
    names: ['Son Le'],
    role: Role.MEMBER,
  },
  {
    id: 'U03L0T172GG',
    email: 'qh@localizedirect.com',
    names: ['Quang Huynh'],
    role: Role.MEMBER,
  },
  {
    id: 'U03NJV8M6BH',
    email: 'dpn@localizedirect.com',
    names: ['Duong Phung'],
    role: Role.MEMBER,
  },
  {
    id: 'U03NJGQ2HAB',
    email: 'kl@localizedirect.com',
    names: ['Khanh Le'],
    role: Role.MEMBER,
  },
  {
    id: 'U03TET29B62',
    email: 'tp@localizedirect.com',
    names: ['Thanh Phan', 'Thanh'],
    role: Role.MEMBER,
  },
  {
    id: 'U044W33PMRA',
    email: 'np@localizedirect.com',
    names: ['Ngan Phan'],
    role: Role.MEMBER,
  },
  {
    id: 'U03DKD4GFLM',
    email: 'truongtrongtin0305@gmail.com',
    names: ['Tin'],
    role: Role.ADMIN,
  },
  {
    id: 'U04AR0TV5M1',
    email: 'qt@localizedirect.com',
    names: ['Quoc Truong', 'Quoc'],
    role: Role.MEMBER,
  },
  {
    id: 'U04C8GMTRMJ',
    email: 'cdm@localizedirect.com',
    names: ['Chau Dang'],
    role: Role.MEMBER,
  },
  {
    id: 'U04F5ALEBN3',
    email: 'mn@localizedirect.com',
    names: ['Minh Nguyen'],
    role: Role.MEMBER,
  },
];
