import { Role } from './types';

export default [
  {
    id: 'U03DKD4GFLM',
    email: 'truongtrongtin0305@gmail.com',
    name: 'Tin',
    role: Role.ADMIN,
  },
  {
    id: 'UBGP2J2PK',
    email: 'ld@localizedirect.com',
    name: 'Lynh',
    role: Role.MEMBER,
  },
  {
    id: 'UK4KAN0QL',
    email: 'tn@localizedirect.com',
    name: 'Truong',
    role: Role.MEMBER,
  },
  {
    id: 'UL85VPR89',
    email: 'gn@localizedirect.com',
    name: 'Giang',
    role: Role.ADMIN,
  },
  {
    id: 'ULNN8L7LY',
    email: 'dng@localizedirect.com',
    name: 'Duong Nguyen',
    role: Role.MEMBER,
  },
  {
    id: 'UNLSN00G4',
    email: 'vtl@localizedirect.com',
    name: 'Trong',
    role: Role.MEMBER,
  },
  {
    id: 'UNPUPE7SQ',
    email: 'kp@localizedirect.com',
    name: 'Khanh Pham',
    role: Role.MEMBER,
  },
  {
    id: 'U010UQL36JV',
    email: 'th@localizedirect.com',
    name: 'Tan',
    role: Role.MEMBER,
  },
  {
    id: 'U011EL24BPS',
    email: 'tin@localizedirect.com',
    name: 'Tin',
    role: Role.ADMIN,
  },
  {
    id: 'U012QKY7YJW',
    email: 'hh@localizedirect.com',
    name: 'Hieu Huynh',
    role: Role.MEMBER,
  },
  {
    id: 'U0183USRRFF',
    email: 'sn@localizedirect.com',
    name: 'Sang',
    role: Role.MEMBER,
  },
  {
    id: 'UUEGP229F',
    email: 'dp@localizedirect.com',
    name: 'Dung',
    role: Role.MEMBER,
  },
  {
    id: 'U01QSGJTA07',
    email: 'qv@localizedirect.com',
    name: 'Quang Vo',
    role: Role.MEMBER,
  },
  {
    id: 'U02ARBPCHSQ',
    email: 'ldv@localizedirect.com',
    name: 'Long',
    role: Role.MEMBER,
  },
  {
    id: 'U02E63EMS1Z',
    email: 'hm@localizedirect.com',
    name: 'Huong',
    role: Role.MEMBER,
  },
  {
    id: 'U02ED23PKGD',
    email: 'tc@localizedirect.com',
    name: 'Steve',
    role: Role.MEMBER,
  },
  {
    id: 'U02EM3B7ZH8',
    email: 'tnn@localizedirect.com',
    name: 'Thy',
    role: Role.MEMBER,
  },
  {
    id: 'U02SFB71Y66',
    email: 'nn@localizedirect.com',
    name: 'Andy',
    role: Role.MEMBER,
  },
  {
    id: 'U037K4B22U8',
    email: 'nnc@localizedirect.com',
    name: 'Jason',
    role: Role.MEMBER,
  },
  {
    id: 'UGMCN8NAV',
    email: 'cm@localizedirect.com',
    name: 'Chau Nguyen',
    role: Role.MEMBER,
  },
  {
    id: 'U03HSG0S599',
    email: 'sla@localizedirect.com',
    name: 'Son',
    role: Role.MEMBER,
  },
  {
    id: 'U03L0T172GG',
    email: 'qh@localizedirect.com',
    name: 'Quang Huynh',
    role: Role.MEMBER,
  },
  {
    id: 'U03NJV8M6BH',
    email: 'dpn@localizedirect.com',
    name: 'Duong Phung',
    role: Role.MEMBER,
  },
  {
    id: 'U03NJGQ2HAB',
    email: 'kl@localizedirect.com',
    name: 'Khanh Le',
    role: Role.MEMBER,
  },
  {
    id: 'U03TET29B62',
    email: 'tp@localizedirect.com',
    name: 'Thanh',
    role: Role.MEMBER,
  },
  {
    id: 'U04AR0TV5M1',
    email: 'qt@localizedirect.com',
    name: 'Quoc',
    role: Role.MEMBER,
  },
  {
    id: 'U04F5ALEBN3',
    email: 'mn@localizedirect.com',
    name: 'Minh',
    role: Role.MEMBER,
  },
  {
    id: 'U04F5ALDRAT',
    email: 'cnp@localizedirect.com',
    name: 'Cuong',
    role: Role.MEMBER,
  },
  {
    id: 'U04SL792FU5',
    email: 'pvn@localizedirect.com',
    name: 'Vu',
    role: Role.MEMBER,
  },
];
